### ISSUE TITLE
Crash when logging inside an Objective-C function.

### ISSUE THREAD

**Issue by antiprosynthesis** [SergiusTheBest/plog#22] opened 2016-04-01 08:47 UTC
Plog crashes when using LOG_INFO inside an Objective-C function. Here is the crash report call stack:

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   plog::util::processFuncName(char const*) + 89 (Util.h:166)
1   plog::Record::getFunc() const + 35 (Record.h:120)
2   plog::TxtFormatter::format(plog::Record const&) + 5139 (TxtFormatter.h:25)
3   plog::RollingFileAppender<plog::TxtFormatter, plog::UTF8Converter>::write(plog::Record const&) + 223 (RollingFileAppender.h:35)
4   plog::Logger<0>::operator+=(plog::Record const&) + 408 (Logger.h:50)
5   -[MyCocoaView mouseDown:] + 62 (toolkitview_cocoa.mm:345)
...

**Comment by SergiusTheBest** [comment] 2016-04-01 11:43
Could you check it on the master version?

**Comment by SergiusTheBest** [comment] 2016-04-07 15:06
@antiprosynthesis Are there any news?

**Comment by antiprosynthesis** [comment] 2016-04-09 12:35
Sorry, I don't have time to check this for the time being. Just thought I'd report it. Great work on this library by the way...

**Comment by SergiusTheBest** [comment] 2016-07-04 12:04
The issue is fixed in 79c7c84bd8f2f7ffdb3396e8e415b05c23a6a9a0.

**Closed by SergiusTheBest** 2016-07-04 12:04 UTC
