### ISSUE TITLE
RollingFileAppender maxFileSize type cast error x64 build

### ISSUE THREAD

**Issue by hdhog** [SergiusTheBest/plog#160] opened 2020-02-18 17:42 UTC
maxFileSize is `size_t` but casting to `long`

![image](https://user-images.githubusercontent.com/386666/74762201-cad8cf80-5296-11ea-9dcc-8a6f9a445820.png)

**Comment by SergiusTheBest** [comment] 2020-02-18 21:07
Do you need support for files > 2GB?

**Comment by hdhog** [comment] 2020-02-19 13:40
yes. log needed splitting to parts on 2Gb.

**Comment by SergiusTheBest** [comment] 2020-03-08 18:18
@hdhog The issue is fixed in the `develop` branch. Please check it out.

**Closed by SergiusTheBest** 2020-03-08 18:18 UTC
