### ISSUE TITLE
WIN32_LEAN_AND_MEAN

### ISSUE THREAD

**Issue by purell** [SergiusTheBest/plog#45] opened 2017-03-15 01:35 UTC
Hi,

What do you think about including 
```
#ifndef WIN32_LEAN_AND_MEAN
    #define WIN32_LEAN_AND_MEAN
#endif
#include <window.h>
```
before including`#include <window.h>` in `Util.h`?

This could prevent many headache of juggling with order of inclusion of `plog.h` when preceding headers already include (winsock.h | winsock2.h) ?

Related problems : 
http://stackoverflow.com/questions/1372480/c-redefinition-header-files-winsock2-h
http://stackoverflow.com/questions/11726958/cant-include-winsock2-h-in-msvc-2010
http://stackoverflow.com/questions/11495589/winsock-redefinition-errors
https://connect.microsoft.com/VisualStudio/feedback/details/3123533/c-problem-windows-h-win32-mean-and-lean ?!?
https://github.com/Microsoft/vcpkg/issues/591
There a many many many other like this...

I already tried to replace `window.h` from Util.h as we should always avoid including `window.h` as it's a mess. But (in a short time) I did not succeed because of functions depending on `WinBase.h` and this former can't be included without including  The Bad and the Ugly `Windows.h`.

Best regards,

**Comment by SergiusTheBest** [comment] 2017-03-21 10:26
Hi,

Unfortunately this cannot be fixed. Defining `WIN32_LEAN_AND_MEAN` here can break code in another places that may not expect `WIN32_LEAN_AND_MEAN` is defined.

One of the solutions is to define `WIN32_LEAN_AND_MEAN` globally at the project level (in makefile, vcxproj, ...). So a developer takes full control and responsibility on this.

I'm considering to remove `windows.h` and declare required stuff by my own. If you have more ideas please share.

**Comment by SergiusTheBest** [comment] 2017-03-21 10:27
Duplicate of #13.

**Comment by purell** [comment] 2017-03-21 14:38
Hi,

I tried replacing `window.h` last week but without success. There always a windows API call that requires `window.h` in addition of the base `.h`. This is very annoying :(

Ex [MultiByteToWideChar](https://msdn.microsoft.com/en-us/library/windows/desktop/dd319072(v=vs.85).aspx)

The required header is `Stringapiset.h` but if you include it without including `window.h` you get a bunch of compiling error.

**Comment by SergiusTheBest** [comment] 2017-03-22 06:54
I've managed to succeed with declaring required winapi functions and removing `windows.h`. I need to run more tests on another compilers.

**Closed** 2017-03-22 22:11 UTC
Labels: duplicate, enhancement
