### ISSUE TITLE
Update plog vcpkg

### ISSUE THREAD

**Issue by Rablidad** [SergiusTheBest/plog#220] opened 2022-08-26 05:12 UTC
Push an update to vcpkg, the current version available in vcpkg is from 2020, which is 2 years outdated, thank you!

**Comment by SergiusTheBest** [comment] 2022-08-26 08:29
Probably you need to update your vcpkg. Because the latest release is pushed to vcpkg a while ago: https://github.com/microsoft/vcpkg/blob/master/ports/plog/portfile.cmake

**Comment by SergiusTheBest** [comment] 2022-12-16 14:43
I hope the issue is resolved, so I'm closing it now.

**Closed by SergiusTheBest** 2022-12-16 14:43 UTC
Labels: question
