### ISSUE TITLE
windows' utf8 encoding problem

### ISSUE THREAD

**Issue by xzzh999** [SergiusTheBest/plog#76] opened 2017-12-04 03:47 UTC
Hi, bigcow, Great work!

When i use the same simple utf8 (in windows use gbk is ok, but i want keep utf8 in all platforms) cpp code with some chinese strings inside, the print and outlog came to  garbled, but it's ok in linux, why?

            LOGV << "this is a test 测试行!" << 1234 << "abc";

windows:  (cvs log file garbled, unknown encoding) 

           2017/12/04;11:12:02.061;VERB;8788;00000000;test@59;"this is a test 娴嬭瘯琛?1234abc"

linux: (cvs log file ok)

           2017/11/29;17:25:45.558;VERB;26492;0;test@46;"this is a test 测试行!1234abc"

**Comment by SergiusTheBest** [comment] 2017-12-04 18:35
Hi,

On Windows `char` is ANSI, not UTF8 (unfortunately). So the string gets wrongly encoded. At the moment the only option is to use `wchar_t`. There is a feature request #69 to forcibly treat `char` as UTF8 but it is not implemented yet.

**Comment by SergiusTheBest** [comment] 2017-12-04 18:37
Duplicate of #69

**Closed by SergiusTheBest** 2017-12-04 18:37 UTC

**Comment by xzzh999** [comment] 2017-12-07 12:16
@SergiusTheBest 
In order  to avoid this, i found on windows use ```msvc 2010 (or +)``` , i can set the source encoding to ```utf8 with bom```, and  vc++ compiler and gcc (i test ```gcc 4.4.6``` on redhat 6.2) can both correctly identified. 
It works perfectly~

**Comment by SergiusTheBest** [comment] 2017-12-07 12:25
Yes, it works but only if a computer locale is correct.

**Comment by SergiusTheBest** [comment] 2023-03-19 17:05
Now plog supports Utf8Everywhere and msvc has `/utf-8` switch.
