### ISSUE TITLE
Support changing log file after plog::init

### ISSUE THREAD

**Issue by hustfox** [SergiusTheBest/plog#151] opened 2019-11-07 00:58 UTC
In my program , I have many items to test serially. In order to make it easier to find the relative log, I want to log each item to a log file whose name maybe \<itemname>+\<datetime>.log etc. 

However, right now if I plog::init with different filenames, the logs are all logged into the first Init file repeately.

**Comment by SergiusTheBest** [comment] 2019-11-08 08:49
Yes, this is a TODO item. For now you can use a solution from #62.

**Comment by SergiusTheBest** [comment] 2019-11-08 08:51
Duplicate of #62

**Comment by SergiusTheBest** [comment] 2019-11-08 08:51
I'm closing this issue, the progress will be tracked in #62.

**Closed by SergiusTheBest** 2019-11-08 08:51 UTC
