### ISSUE TITLE
No Log File Produced

### ISSUE THREAD

**Issue by MurrelektronikPatrick** [SergiusTheBest/plog#224] opened 2022-09-27 09:14 UTC
I included the plog/include directory in my qt project on my linux/ubuntu distribution and initialized with 
```C++
plog::init(plog::info, "/home/patrick/Desktop/ApplicationUILog.log", 1000000, 5);
PLOG(plog::debug) << "Created Logger";
```

I searched on my whole computer for the desired log file but didn't find it.
Is there any know solution for it?

**Comment by SergiusTheBest** [comment] 2022-09-27 09:23
You set the log severity to `plog::info`. That means that `plog::debug` will be filtered out.

**Comment by supermyle** [comment] 2022-10-25 20:13
@MurrelektronikPatrick In QtCreator if you created it like this and your project is named for example Patrick it should show up in your build folder at build-Patrick-Desktop_Qt_6_4_0_GCC_64bit-Debug/ApplicationUILog.log

Change your init statement to this
plog::init(plog::info, "ApplicationUILog.log", 1000000, 5);

and then build/run your program and see if your file shows up, once you know it works, try the custom route again at /home/patrick/Desktop/

**Comment by SergiusTheBest** [comment] 2022-12-16 16:11
I hope the issue is resolved, so I'm closing it now.

**Closed by SergiusTheBest** 2022-12-16 16:11 UTC
Labels: question
